# -*- coding: utf-8 -*-
"""Diabetes Prediction & Treatment Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kN4hambauIGfhOtPyxV8tRIwkdI0IGYi
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import warnings

warnings.filterwarnings('ignore')

class DiabetesAnalysisSystem:
    def __init__(self):
        """Initializes the three models that will be trained."""
        self.status_model = LogisticRegression(random_state=42)
        self.type_model = RandomForestClassifier(random_state=42)
        self.treatment_model = RandomForestClassifier(random_state=42)
        self.encoders = {}
        self.feature_columns = []

    def _prepare_data(self, df):
        """
        Preprocesses the data by encoding categorical features into numbers.
        Saves the encoders to be used on new patient data.
        """
        processed_df = df.copy()
        # Encode 'Kidney_Function' as it's a categorical feature
        le = LabelEncoder()
        processed_df['Kidney_Function'] = le.fit_transform(processed_df['Kidney_Function'])
        self.encoders['Kidney_Function'] = le # Save encoder
        return processed_df

    def train_models(self, file_path):
        """
        Loads the data and trains all three predictive models.
        """
        # --- Load and Prepare Data ---
        try:
            df = pd.read_csv(file_path)
        except FileNotFoundError:
            print(f"Error: The file '{file_path}' was not found.")
            return

        df_processed = self._prepare_data(df)
        self.feature_columns = ['Age', 'BMI', 'HbA1c', 'Fasting_Glucose', 'Family_History', 'Hypertension', 'Is_Pregnant', 'Kidney_Function']

        # --- 1. Train Diabetes Status Model (Binary Classification) ---
        X_status = df_processed[self.feature_columns]
        y_status = df_processed['Diabetes_Status']
        self.status_model.fit(X_status, y_status)
        print("1. Diabetes status prediction model trained.")

        # --- Prepare data for the next two models (only use diabetic patients) ---
        df_diabetic = df_processed[df_processed['Diabetes_Status'] == 1].copy()
        if df_diabetic.empty:
            print("Warning: No diabetic patients in the dataset to train type and treatment models.")
            return

        X_diabetic = df_diabetic[self.feature_columns]

        # --- 2. Train Diabetes Type Model (Multi-class Classification) ---
        y_type = df_diabetic['Diabetes_Type']
        self.type_model.fit(X_diabetic, y_type)
        print("2. Diabetes type prediction model trained.")

        # --- 3. Train Treatment Recommendation Model (Multi-class Classification) ---
        y_treatment = df_diabetic['Recommended_Treatment']
        self.treatment_model.fit(X_diabetic, y_treatment)
        print("3. Treatment recommendation model trained.")
        print("-" * 30)

    def generate_patient_report(self, patient_data):
        """
        Takes new patient data, runs it through the prediction pipeline,
        and prints a comprehensive report.
        """
        print("\n--- Generating New Patient Report ---")
        print(f"Patient Input: {patient_data}")

        # --- Prepare new patient data ---
        patient_df = pd.DataFrame([patient_data])
        # Encode categorical features using saved encoders
        patient_df['Kidney_Function'] = self.encoders['Kidney_Function'].transform(patient_df['Kidney_Function'])

        # Ensure correct column order
        patient_df = patient_df[self.feature_columns]

        # --- Prediction Pipeline ---
        # Step 1: Predict Diabetes Status
        status_prediction = self.status_model.predict(patient_df)[0]
        status_proba = self.status_model.predict_proba(patient_df)[0]

        print("\n--- DIAGNOSIS ---")
        if status_prediction == 0:
            confidence = status_proba[0]
            print(f"Prediction: NOT DIABETIC (Confidence: {confidence:.2%})")
            print("Recommendation: Focus on Lifestyle Modification (Diet and Exercise).")
        else:
            confidence = status_proba[1]
            print(f"Prediction: DIABETIC (Confidence: {confidence:.2%})")

            # Step 2: Predict Diabetes Type
            type_prediction = self.type_model.predict(patient_df)[0]
            type_proba = self.type_model.predict_proba(patient_df)[0]
            type_confidence = type_proba.max()
            print(f"Predicted Diabetes Type: {type_prediction} (Confidence: {type_confidence:.2%})")

            # Step 3: Recommend Treatment
            treatment_prediction = self.treatment_model.predict(patient_df)[0]
            treatment_proba = self.treatment_model.predict_proba(patient_df)[0]
            treatment_confidence = treatment_proba.max()

            print("\n--- TREATMENT PLAN ---")
            print(f"Recommended Treatment: {treatment_prediction} (Confidence: {treatment_confidence:.2%})")
        print("-" * 30)

# --- Main Execution ---
if __name__ == '__main__':
    # Initialize the system
    analysis_system = DiabetesAnalysisSystem()

    # Train the models using the data from your CSV file
    # Make sure 'diabetes_enhanced_data.csv' is in the same directory as the script
    analysis_system.train_models('diabetes_enhanced_data.csv')

    # --- Use the trained system to analyze new patients ---

    # Example 1: A patient who is likely to be diagnosed with Type 2 Diabetes
    patient_1 = {
        'Age': 58,
        'BMI': 33.1,
        'HbA1c': 7.4,
        'Fasting_Glucose': 152,
        'Family_History': 1,
        'Hypertension': 1,
        'Is_Pregnant': 0,
        'Kidney_Function': 'Good' # Use the text label, the system will encode it
    }
    analysis_system.generate_patient_report(patient_1)

    # Example 2: A patient who is likely healthy
    patient_2 = {
        'Age': 40,
        'BMI': 24.0,
        'HbA1c': 5.5,
        'Fasting_Glucose': 98,
        'Family_History': 0,
        'Hypertension': 0,
        'Is_Pregnant': 0,
        'Kidney_Function': 'Good'
    }
    analysis_system.generate_patient_report(patient_2)

    # Example 3: A younger patient who might be Type 1
    patient_3 = {
        'Age': 26,
        'BMI': 26.2,
        'HbA1c': 7.8,
        'Fasting_Glucose': 165,
        'Family_History': 0,
        'Hypertension': 0,
        'Is_Pregnant': 0,
        'Kidney_Function': 'Good'
    }
    analysis_system.generate_patient_report(patient_3)