# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CLmHLrAYnElpnHVRydDwW0I2LH1IJTe0
"""

let
    Source = Python.Execute("
import pandas as pd
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
import warnings

warnings.filterwarnings('ignore')

# --- HYBRID CLASS: Combines Classification and Regression ---
class DiabetesAnalysisSystem:
    def __init__(self):
        # Models for classification (Diagnosis)
        self.status_model = LogisticRegression(random_state=42)
        self.type_model = RandomForestClassifier(random_state=42)

        # Model for regression (Effectiveness)
        self.effectiveness_model = RandomForestRegressor(n_estimators=100, random_state=42)

        self.classification_features = []
        self.regression_features = []
        self.possible_treatments = []
        self.encoders = {}

    def _prepare_classification_data(self, df):
        df_processed = df.copy()
        le = LabelEncoder()
        df_processed['Kidney_Function'] = le.fit_transform(df_processed['Kidney_Function'])
        self.encoders['Kidney_Function'] = le
        return df_processed

    def _prepare_regression_data(self, df):
        df_processed = df.copy()
        df_processed = pd.get_dummies(df_processed, columns=['Kidney_Function', 'Assigned_Treatment'], drop_first=True)
        return df_processed

    def train_models(self, classification_path, regression_path):
        # --- Train Classification Models ---
        df_class = pd.read_csv(classification_path)
        df_class_processed = self._prepare_classification_data(df_class)
        self.classification_features = ['Age', 'BMI', 'HbA1c', 'Fasting_Glucose', 'Family_History', 'Hypertension', 'Is_Pregnant', 'Kidney_Function']

        X_status = df_class_processed[self.classification_features]
        y_status = df_class_processed['Diabetes_Status']
        self.status_model.fit(X_status, y_status)

        df_diabetic = df_class_processed[df_class_processed['Diabetes_Status'] == 1].copy()
        if not df_diabetic.empty:
            X_diabetic_type = df_diabetic[self.classification_features]
            y_type = df_diabetic['Diabetes_Type']
            self.type_model.fit(X_diabetic_type, y_type)

        # --- Train Regression Model ---
        df_reg = pd.read_csv(regression_path)
        self.possible_treatments = df_reg['Assigned_Treatment'].unique().tolist()
        df_reg_processed = self._prepare_regression_data(df_reg)

        y_reg = df_reg_processed['Future_HbA1c']
        self.regression_features = [col for col in df_reg_processed.columns if col not in ['Patient_ID', 'Diabetes_Status', 'Diabetes_Type', 'Future_HbA1c']]
        X_reg = df_reg_processed[self.regression_features]
        self.effectiveness_model.fit(X_reg, y_reg)

    def generate_plan(self, patient_data):
        # --- Step 1: Predict Diagnosis ---
        patient_df_class = pd.DataFrame([patient_data])
        patient_df_class['Kidney_Function'] = self.encoders['Kidney_Function'].transform(patient_df_class['Kidney_Function'])
        X_patient_class = patient_df_class[self.classification_features]

        status_prediction = self.status_model.predict(X_patient_class)[0]
        diagnosis_result = {}

        if status_prediction == 0:
            diagnosis_result['Diagnosis'] = 'Not Diabetic'
            diagnosis_result['Diabetes_Type'] = 'N/A'
        else:
            diagnosis_result['Diagnosis'] = 'Diabetic'
            diagnosis_result['Diabetes_Type'] = self.type_model.predict(X_patient_class)[0]

        # --- Step 2: Predict Treatment Effectiveness ---
        treatment_results = []
        for treatment in self.possible_treatments:
            patient_instance = patient_data.copy()
            patient_instance['Assigned_Treatment'] = treatment
            patient_df_reg = pd.DataFrame([patient_instance])
            patient_df_reg_processed = pd.get_dummies(patient_df_reg)
            aligned_df = patient_df_reg_processed.reindex(columns=self.regression_features, fill_value=0)
            predicted_hba1c = self.effectiveness_model.predict(aligned_df)[0]

            # Combine all info for each row
            combined_info = {
                **patient_data,
                **diagnosis_result,
                'Treatment_Option': treatment,
                'Predicted_Future_HbA1c': round(predicted_hba1c, 2)
            }
            treatment_results.append(combined_info)

        return treatment_results

# --- POWER BI EXECUTION BLOCK ---
patient_input = dataset.to_dict('records')[0]

# Define paths for both data files
classification_file_path = 'C:/code/Diabetes_Treatment_Planner/1_Data_Sources/diabetes_enhanced_data.csv'
regression_file_path = 'C:/code/Diabetes_Treatment_Planner/1_Data_Sources/diabetes_treatment_outcomes.csv'

# Initialize and train the hybrid system
analysis_system = DiabetesAnalysisSystem()
analysis_system.train_models(classification_file_path, regression_file_path)

# Generate the full plan
full_plan = analysis_system.generate_plan(patient_input)

# Convert the final list of dictionaries into a DataFrame
output_df = pd.DataFrame(full_plan)
", [dataset=PatientInputTable]),
    output_df1 = Source{[Name="output_df"]}[Value],
    #"Changed Type" = Table.TransformColumnTypes(output_df1,{{"Predicted_Future_HbA1c", type number}})
in
    #"Changed Type"