table output_df
	lineageTag: bbcd1685-c3c6-4b3b-aed6-84da6ad5d192

	measure 'Confidence Score' = SELECTEDVALUE(output_df[Diagnosis_Confidence])
		lineageTag: 4ae84953-19ff-4f4e-95ab-9e51cac32238

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Treatment_Option
		dataType: string
		lineageTag: 99048d19-61ad-464b-9f86-24b9695d4fa5
		summarizeBy: none
		sourceColumn: Treatment_Option

		annotation SummarizationSetBy = Automatic

	column Predicted_Future_HbA1c
		dataType: double
		lineageTag: d70cf713-291d-4e33-8135-8cf7cf24098a
		summarizeBy: sum
		sourceColumn: Predicted_Future_HbA1c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Age
		dataType: string
		lineageTag: b3d30b72-bf0e-4b9b-bae9-00c33b67f7b7
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column BMI
		dataType: string
		lineageTag: ff6d8b70-ca06-45e7-b848-15bc64254ebc
		summarizeBy: none
		sourceColumn: BMI

		annotation SummarizationSetBy = Automatic

	column HbA1c
		dataType: string
		lineageTag: 3ea76d0c-e1be-4a38-ae27-f6c89e7d9fcf
		summarizeBy: none
		sourceColumn: HbA1c

		annotation SummarizationSetBy = Automatic

	column Fasting_Glucose
		dataType: string
		lineageTag: ab772f31-08e4-42f3-bd6d-6badf416e290
		summarizeBy: none
		sourceColumn: Fasting_Glucose

		annotation SummarizationSetBy = Automatic

	column Family_History
		dataType: string
		lineageTag: 40309a03-dc1a-4782-9fd1-4a00468af80a
		summarizeBy: none
		sourceColumn: Family_History

		annotation SummarizationSetBy = Automatic

	column Hypertension
		dataType: string
		lineageTag: c80ddba6-c0d1-41c4-9695-db87a9ff7b05
		summarizeBy: none
		sourceColumn: Hypertension

		annotation SummarizationSetBy = Automatic

	column Is_Pregnant
		dataType: string
		lineageTag: 831fed69-bdb4-4d62-95ec-1d2908cc45c6
		summarizeBy: none
		sourceColumn: Is_Pregnant

		annotation SummarizationSetBy = Automatic

	column Kidney_Function
		dataType: string
		lineageTag: 8dae9459-1662-4995-909c-bfce85eb9d1a
		summarizeBy: none
		sourceColumn: Kidney_Function

		annotation SummarizationSetBy = Automatic

	column Diagnosis
		dataType: string
		lineageTag: 0826ee33-6bee-4020-a926-444541721a94
		summarizeBy: none
		sourceColumn: Diagnosis

		annotation SummarizationSetBy = Automatic

	column Diabetes_Type
		dataType: string
		lineageTag: 26b50376-04ca-4106-9c02-a748cb01b6b9
		summarizeBy: none
		sourceColumn: Diabetes_Type

		annotation SummarizationSetBy = Automatic

	partition output_df = m
		mode: import
		source = ```
				let
				    Source = Python.Execute("
				import pandas as pd
				from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
				from sklearn.linear_model import LogisticRegression
				from sklearn.preprocessing import LabelEncoder
				import warnings
				
				warnings.filterwarnings('ignore')
				
				# --- HYBRID CLASS: Combines Classification and Regression ---
				class DiabetesAnalysisSystem:
				    def __init__(self):
				        # Models for classification (Diagnosis)
				        self.status_model = LogisticRegression(random_state=42)
				        self.type_model = RandomForestClassifier(random_state=42)
				        
				        # Model for regression (Effectiveness)
				        self.effectiveness_model = RandomForestRegressor(n_estimators=100, random_state=42)
				        
				        self.classification_features = []
				        self.regression_features = []
				        self.possible_treatments = []
				        self.encoders = {}
				
				    def _prepare_classification_data(self, df):
				        df_processed = df.copy()
				        le = LabelEncoder()
				        df_processed['Kidney_Function'] = le.fit_transform(df_processed['Kidney_Function'])
				        self.encoders['Kidney_Function'] = le
				        return df_processed
				
				    def _prepare_regression_data(self, df):
				        df_processed = df.copy()
				        df_processed = pd.get_dummies(df_processed, columns=['Kidney_Function', 'Assigned_Treatment'], drop_first=True)
				        return df_processed
				
				    def train_models(self, classification_path, regression_path):
				        # --- Train Classification Models ---
				        df_class = pd.read_csv(classification_path)
				        df_class_processed = self._prepare_classification_data(df_class)
				        self.classification_features = ['Age', 'BMI', 'HbA1c', 'Fasting_Glucose', 'Family_History', 'Hypertension', 'Is_Pregnant', 'Kidney_Function']
				        
				        X_status = df_class_processed[self.classification_features]
				        y_status = df_class_processed['Diabetes_Status']
				        self.status_model.fit(X_status, y_status)
				
				        df_diabetic = df_class_processed[df_class_processed['Diabetes_Status'] == 1].copy()
				        if not df_diabetic.empty:
				            X_diabetic_type = df_diabetic[self.classification_features]
				            y_type = df_diabetic['Diabetes_Type']
				            self.type_model.fit(X_diabetic_type, y_type)
				
				        # --- Train Regression Model ---
				        df_reg = pd.read_csv(regression_path)
				        self.possible_treatments = df_reg['Assigned_Treatment'].unique().tolist()
				        df_reg_processed = self._prepare_regression_data(df_reg)
				        
				        y_reg = df_reg_processed['Future_HbA1c']
				        self.regression_features = [col for col in df_reg_processed.columns if col not in ['Patient_ID', 'Diabetes_Status', 'Diabetes_Type', 'Future_HbA1c']]
				        X_reg = df_reg_processed[self.regression_features]
				        self.effectiveness_model.fit(X_reg, y_reg)
				
				    def generate_plan(self, patient_data):
				        # --- Step 1: Predict Diagnosis ---
				        patient_df_class = pd.DataFrame([patient_data])
				        patient_df_class['Kidney_Function'] = self.encoders['Kidney_Function'].transform(patient_df_class['Kidney_Function'])
				        X_patient_class = patient_df_class[self.classification_features]
				        
				        status_prediction = self.status_model.predict(X_patient_class)[0]
				        diagnosis_result = {}
				
				        if status_prediction == 0:
				            diagnosis_result['Diagnosis'] = 'Not Diabetic'
				            diagnosis_result['Diabetes_Type'] = 'N/A'
				        else:
				            diagnosis_result['Diagnosis'] = 'Diabetic'
				            diagnosis_result['Diabetes_Type'] = self.type_model.predict(X_patient_class)[0]
				
				        # --- Step 2: Predict Treatment Effectiveness ---
				        treatment_results = []
				        for treatment in self.possible_treatments:
				            patient_instance = patient_data.copy()
				            patient_instance['Assigned_Treatment'] = treatment
				            patient_df_reg = pd.DataFrame([patient_instance])
				            patient_df_reg_processed = pd.get_dummies(patient_df_reg)
				            aligned_df = patient_df_reg_processed.reindex(columns=self.regression_features, fill_value=0)
				            predicted_hba1c = self.effectiveness_model.predict(aligned_df)[0]
				            
				            # Combine all info for each row
				            combined_info = {
				                **patient_data, 
				                **diagnosis_result,
				                'Treatment_Option': treatment,
				                'Predicted_Future_HbA1c': round(predicted_hba1c, 2)
				            }
				            treatment_results.append(combined_info)
				            
				        return treatment_results
				
				# --- POWER BI EXECUTION BLOCK ---
				patient_input = dataset.to_dict('records')[0]
				
				# Define paths for both data files
				classification_file_path = 'C:/code/Diabetes_Treatment_Planner/1_Data_Sources/diabetes_enhanced_data.csv'
				regression_file_path = 'C:/code/Diabetes_Treatment_Planner/1_Data_Sources/diabetes_treatment_outcomes.csv'
				
				# Initialize and train the hybrid system
				analysis_system = DiabetesAnalysisSystem()
				analysis_system.train_models(classification_file_path, regression_file_path)
				
				# Generate the full plan
				full_plan = analysis_system.generate_plan(patient_input)
				
				# Convert the final list of dictionaries into a DataFrame
				output_df = pd.DataFrame(full_plan)
				", [dataset=PatientInputTable]),
				    output_df1 = Source{[Name="output_df"]}[Value],
				    #"Changed Type" = Table.TransformColumnTypes(output_df1,{{"Predicted_Future_HbA1c", type number}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

